#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
compton --config ~/.config/compton/compton.conf &
wname L3GD &
feh --bg-fill ~/.alOS/pictures/Wallpaper.png &
~/.config/polybar/launch.sh &
killall mate-notification-daemon; dunst &

bspc config pointer_modifier mod1

~/.config/bspwm/display-detect.sh
~/.config/bspwm/desktop-multiplex.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a fileExplorer state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
